spring:
  datasource:
    url: jdbc:mysql://localhost:3306/address_approval?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1019
    driver-class-name: com.mysql.cj.jdbc.Driver